WEB_INCIDENTS = [
  "Late-night hotfix broke an invoicing job, and the rollback left customer data in a corrupted state.",
  "A feature flag rollout triggered unexpected writes, corrupting user preferences across environments.",
  "A background job retried failed payments indefinitely, silently charging some customers twice.",
  "A schema change removed a nullable column — and the next deploy crashed every signup.",
  "A stale config in staging masked a 503 loop in production for nearly 3 hours.",
  "A malformed webhook payload bypassed validation and poisoned the audit trail.",
  "A caching layer upgrade dropped all write-through logic — production data diverged within minutes.",
  "Rate limits were enforced globally, not per user — and a single customer blocked the entire API.",
  "A misconfigured health check caused a node rotation storm that degraded performance company-wide.",
  "A timezone bug in a cron expression delayed invoice generation by 12 hours, causing them to be off by one day.",
  "A feature flag rollout triggered unexpected writes, corrupting user preferences across environments.",
  "A background job retried failed payments indefinitely, silently charging some customers twice.",
  "A schema change removed a nullable column — and the next deploy crashed every signup.",
  "A stale config in staging masked a 503 loop in production for nearly 3 hours.",
  "A malformed webhook payload bypassed validation and poisoned the audit trail.",
  "A caching layer upgrade dropped all write-through logic — production data diverged within minutes.",
  "A dead letter queue silently filled for weeks until disk pressure triggered cascading service failures.",
  "CDN cache corruption served outdated JavaScript to logged-in users, breaking CSRF tokens site-wide.",
  "A runaway feature flag rollout enabled beta auth logic for legacy tenants, locking thousands out.",
  "Retry storm from a third-party API outage spiked database connections past max limits — backups stalled, failover failed.",
  "Deployment rollback restored an old cron schedule — re-enabling a long-deprecated database vacuum job that blocked writes.",
  "An SSO redirect loop wasn't caught by monitoring because all retries were returning HTTP 200s.",
  "A config typo set Redis expiration to 60 minutes instead of 60 seconds — session drift emerged 4 hours later.",
  "Database replica lag masked writes for one region, and dashboards kept showing partial success.",
  "An old default in the HAProxy config started dropping gRPC streams during idle periods.",
  "Orchestration mistakenly marked a primary node as healthy based on stale metrics — it rejoined mid-rollback.",
  "A DNS misconfiguration split traffic across environments — staging and prod merged for 15 minutes.",
  "An expired certificate in a rarely-touched code path blocked password resets across all mobile clients.",
  "Billing code silently failed when a new enum value was introduced — no one noticed until revenue dropped.",
  "An environment variable shadowed a secrets file, nulling out access to the encryption key in prod only.",
  "A CI optimization skipped tests for renamed files — a commit landed with broken migrations.",
  "Request IDs were being reused by a flaky load balancer, corrupting trace correlation across microservices.",
  "A background migration clashed with live writes, deadlocking the customer record for every new signup.",
  "A logic bug in rate limiting treated IPv6 /64s as individual addresses — an entire org got blocked.",
  "A GCS bucket policy changed without alerting — exports failed silently for 3 weeks.",
  "A new linter rule auto-fixed prod-only code with test-only defaults — rollback took hours to identify.",
  "Legacy tokens weren’t invalidated on password reset — ex-employees retained admin access.",
  "A metrics ingest spike dropped critical alert series, delaying detection of a full outage by 12 minutes.",
  "An unbounded retry loop in the email worker retried failed sends every second — 2M messages queued overnight.",
  "A Redis failover removed volatile keys mid-transaction — idempotency collapsed across retries.",
  "A log shipper misconfigured file rotation — disk filled, kubelet evicted the wrong pods.",
  "Deployment scripts accidentally skipped an `await` — half of prod never restarted.",
  "A new payment gateway integration didn’t respect ISO-8601 — timestamps rounded into the future.",
  "A user-supplied webhook response triggered a nested render in Rails — internal SSR loop crashed the app server.",
  "A cloud provider AZ degraded silently — autoscaler spun up new nodes in the same zone.",
  "A backup restore swapped environment IDs — all access controls pointed to the wrong tenant space.",
  "Alerts were hardcoded to a Slack webhook URL — the channel was deleted months ago.",
  "Two overlapping rollouts clobbered each other's state — no one owned the fallback logic.",
  "The new dependency scanner ran out of memory mid-deploy — leaving zombie containers live for hours.",
  "An intern copied production data into staging and accidentally emailed 30k real users with test content.",
  "A flaky queue connection didn't raise errors — it silently dropped 12 hours of job dispatches.",
  "An old failover script was triggered manually and promoted a cold standby with a 2-day-old snapshot.",
  "A new serializer defaulted to camelCase — downstream services using snake_case rejected every payload.",
  "Rate limiting logic used the wrong time unit — limits reset once per hour instead of per minute.",
  "A typo in a Terraform variable wiped the IAM policy for the metrics bucket — dashboards went dark globally.",
  "An aggressive GC tuning setting from a benchmark environment made it to prod — CPU usage quadrupled.",
  "Alerts were filtered by a deprecated label — SEV-1s were routed to a retired PagerDuty schedule.",
  "Cross-region replication lag caused an eventually consistent store to overwrite newly written data.",
  "A prod config flag was toggled from the staging dashboard — no audit trail, no rollback button.",
  "A race condition in file upload logic caused a zero-byte overwrite for high-concurrency paths.",
  "A read replica lag masked write failures — the team celebrated green dashboards for a week.",
  "Two teams renamed the same protobuf field in different services. Rollbacks didn't help.",
  "An observability agent upgrade exposed internal metadata over a public endpoint.",
  "A batch import script skipped rows with nulls — and nulls were the rows we cared about.",
  "A 'safe to retry' error surfaced on a non-idempotent endpoint, corrupting state on every retry.",
  "A metrics alert fired too early, masking the real issue: a slow leak in session expiration logic.",
  "A circuit breaker tripped for the wrong fallback — stale data got served as live inventory.",
  "A deploy skipped a migration. The app didn't crash, but the behavior drifted for weeks.",
  "The security team added a required header. Half the integrations broke silently.",
  "A rollback restored code, but not the associated IAM policy — every request now failed with 403.",
  "A database promotion failed mid-cutover — both replicas accepted writes for 9 minutes.",
  "An edge cache stored sensitive headers and replayed them across users.",
  "An expired certificate broke OAuth login for every enterprise customer.",
  "SSO callback responses weren't validated — users were logged in as admins.",
  "The primary key overflowed and started assigning duplicate IDs.",
  "A backup restore silently skipped one table — it took two weeks to notice.",
  "Staging secrets were used in production — and rotated automatically at midnight.",
  "A pagination loop DOSed the billing endpoint, breaking every invoice export job.",
  "The rollout script updated the wrong feature flag, shipping an unfinished workflow to prod.",
  "A queue retry storm overwhelmed the read replica and silently degraded performance.",
  "The search index lagged behind by 12 hours — nobody knew until a customer asked.",
  "CI ran against the wrong branch, and deployed staging code to production.",
  "The incident responder rebooted the wrong cluster — recovery took 2 hours longer.",
  "An unversioned config changed behavior between deploys and caused a data wipe.",
  "A roll-forward fixed the bug but introduced a worse one — and nobody rolled back.",
  "Log truncation dropped the root cause of the SEV — it never made it to the postmortem.",
  "A test environment got promoted to production — it took down all customer access.",
  "A firewall rule was updated without coordination — half of prod went dark.",
  "The failover region wasn't pre-warmed — the handoff timed out during the SEV.",
  "A GCP IAM role was deleted by a terraform drift fix — and no one noticed until Monday.",
  "The metrics dashboard showed 99.9% uptime — because the health check always returned 200.",
  "An analytics SDK flooded the network with retries — it masked actual outages.",
  "The API gateway dropped all DELETE requests due to a malformed regex.",
  "A DNS misconfiguration routed staging traffic into production."
]